version: "3.1"

services:
  scheduler:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-scheduler
    volumes:
      - /home/aslan/dask-docker:/home/jovyan/volume
    environment:
      EXTRA_CONDA_PACKAGES: ${EXTRA_CONDA_PACKAGES}
      EXTRA_PIP_PACKAGES: ${EXTRA_PIP_PACKAGES}
      EXTRA_APT_PACKAGES: ${EXTRA_APT_PACKAGES}
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-worker
    volumes:
      - /home/aslan/dask-docker:/home/jovyan/volume
    environment:
      EXTRA_CONDA_PACKAGES: ${EXTRA_CONDA_PACKAGES}
      EXTRA_PIP_PACKAGES: ${EXTRA_PIP_PACKAGES}
      EXTRA_APT_PACKAGES: ${EXTRA_APT_PACKAGES}
    command: ["dask-worker", "tcp://scheduler:8786"]

  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    image: daskdev/dask-notebook
    hostname: notebook
    volumes:
      - /home/aslan/dask-docker:/home/jovyan/volume
    ports:
      - "8888:8888"
    environment:
      EXTRA_CONDA_PACKAGES: ${EXTRA_CONDA_PACKAGES}
      EXTRA_PIP_PACKAGES: ${EXTRA_PIP_PACKAGES}
      EXTRA_APT_PACKAGES: ${EXTRA_APT_PACKAGES}
      DASK_SCHEDULER_ADDRESS: ${DASK_SCHEDULER_ADDRESS}
