version: "3.1"

services:
  scheduler:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-scheduler
    environment:
      EXTRA_CONDA_PACKAGES: ${EXTRA_CONDA_PACKAGES}
      EXTRA_PIP_PACKAGES: ${EXTRA_PIP_PACKAGES}
      EXTRA_APT_PACKAGES: ${EXTRA_APT_PACKAGES}
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    build:
      context: ./base
      dockerfile: Dockerfile
    image: daskdev/dask
    hostname: dask-worker
    environment:
      EXTRA_CONDA_PACKAGES: ${EXTRA_CONDA_PACKAGES}
      EXTRA_PIP_PACKAGES: ${EXTRA_PIP_PACKAGES}
      EXTRA_APT_PACKAGES: ${EXTRA_APT_PACKAGES}
    command: ["dask-worker", "tcp://scheduler:8786"]

  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    image: daskdev/dask-notebook
    hostname: notebook
    environment:
      EXTRA_CONDA_PACKAGES: ${EXTRA_CONDA_PACKAGES}
      EXTRA_PIP_PACKAGES: ${EXTRA_PIP_PACKAGES}
      EXTRA_APT_PACKAGES: ${EXTRA_APT_PACKAGES}
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
